### PR TITLE
we no longer use the apt user group

### PR DESCRIPTION
**Pull request by gqqnbig**
reviewers please know why and is it complete?

### CODE REVIEW

**Comment by gqqnbig** [comment]
in the past we didn't implement conda, so we would allow users to run sudo. But with the apparent drawback, we ask users to config conda environments rather than muggling with the global system.

**Comment by gqqnbig** [comment]
@luoyuqi-lab  Well.. I looked it again, why do we still have 

https://github.com/gqqnbig/shine-cluster/blob/c4420fc57fcd9483163b9bcb2c40814e01b81d7f/cluster-add-user/cluster-add-user.sh#L41

If we've been divorced from aptuser, we should delete all occurrences of it in the repo, right? Like you break up with your girlfriend, you delete all her photos.

**Comment by gqqnbig** [comment]
don't tell me you don't 🐶

**Comment by luoyuqi-lab** [comment]
> @luoyuqi-lab Well.. I looked it again, why do we still have
> 
> https://github.com/gqqnbig/shine-cluster/blob/c4420fc57fcd9483163b9bcb2c40814e01b81d7f/cluster-add-user/cluster-add-user.sh#L41
> 
> If we've been divorced from aptuser, we should delete all occurrences of it in the repo, right? 

Sure, I could find and delete all aptuser, which I think maybe not only in line 41.

**Pull request merged**
