### PR TITLE
Add a file with English idioms for daily tips.

### PR DESCRIPTION
**Pull request by luoyuqi-lab**
Add a file that includes 100 English Idioms for daily tips. For randomly showing for server users when they log in.

Location is \shine-cluster\login\etc\daily-tips.

### CODE REVIEW

**Comment by gqqnbig** [comment]
1. Fix the PR title
2. Rename the file to "Expressions, English idims"(?). Before the comma is the chapter name, after is the book name.
3. Make sure bash can load the script

**Comment by luoyuqi-lab** [comment]
@gqqnbig Can you take a look?

**Comment by gqqnbig** [comment]
Moving forward, please create a branch in this repo, not in your own fork, for easy operation.

**Comment by gqqnbig** [comment]
putty_bE3k0xy50x

Can you check the iffy coloring? I use VIM. I don't know if its VIM's bug or your bug.

**Comment by luoyuqi-lab** [comment]
> putty_bE3k0xy50x
> 
> Can you check the iffy coloring? I use VIM. I don't know if its VIM's bug or your bug.

I also use VIM,  and I will check it tomorrow, use the lab's PC.

**Comment by gqqnbig** [comment]
The authority ranking I embrace is OED > Printed books > random online wesbites.

I did find some content match Merriam-Webster or Cambridge online dictionary, but if you have a printed Merriam-Webster I will be delighted to accept them. The content of printed book won't change so it's easy for reference and verification.

To sum up, can you check my changes and see if they are OK? You want to make sure my underline works. If everything works for you, you click the **Merge** button. Thanks!

**Comment by gqqnbig** [comment]
Ahhh, I found the file has idioms from other chapters.. I didn't expect that.

**Pull request merged**
