### PR TITLE
Check bad tips files

### PR DESCRIPTION
**Pull request by luoyuqi-lab**

### CODE REVIEW

**Comment by gqqnbig** [comment]
firefox_SgMSRBG8PC

Can you go one step further, remove all other commits, and only leave the last three? You will use the git rebase command.

**Comment by luoyuqi-lab** [comment]
Using [Shellcheck](https://github.com/koalaman/shellcheck) in workflows to check bash scripts (not only daily-tips file) error when Push or PR.

Because of `--severity=error`, some information would not be shown including warnings.

Please check it. Thanks. @gqqnbig

**Comment by gqqnbig** [comment]
for #109

**Comment by gqqnbig** [comment]
merged 318d677

**Pull request closed without merging**
